---
- name: Converge
  hosts: all
  pre_tasks:
    - name: "include role vars ..."
      include_vars:
        file: ../../defaults/main.yml
    - name: "fetch server deb ..."
      get_url:
        url: "https://download.checkmk.com/checkmk/2.0.0p18/check-mk-raw-{{ checkmk_agent_version }}_0.bullseye_amd64.deb"
        dest: "/var/tmp//check-mk-raw-{{ checkmk_agent_version }}_0.bullseye_amd64.deb"
        force: false
        mode: 0600
    - name: "extract server deb ..."
      command: "dpkg-deb -x /var/tmp/check-mk-raw-{{ checkmk_agent_version }}_0.bullseye_amd64.deb /var/tmp/check-mk-raw"
      args:
        creates: "/var/tmp/check-mk-raw/opt/omd/versions/{{ checkmk_agent_version }}.cre/share/check_mk/agents/{{ checkmk_agent_deb }}"
    - name: "get agent dep from extracted files ..."
      copy:
        src: "/var/tmp/check-mk-raw/opt/omd/versions/{{ checkmk_agent_version }}.cre/share/check_mk/agents/{{ checkmk_agent_deb }}"
        dest: "/var/tmp/{{ checkmk_agent_deb }}"
        mode: 0600
        remote_src: true
  tasks:
    - name: "Include ansible-role-checkmkagent"
      include_role:
        name: "ansible-role-checkmkagent"
  post_tasks:
    - name: "Install netcat-openbsd"
      apt:
        name: netcat-openbsd
    - name: "Test checkmk agent"
      command: /bin/nc.openbsd -N -w 5 127.0.0.1 6556
      register: nc
      changed_when: false
    - assert:
        that:
          - nc.stdout_lines[0] == '<<<check_mk>>>'

