---
driver:
  name: docker
platforms:
  - name: instance
    image: debian:${MOLECULE_DISTRO:-debian11}
    dockerfile: Dockerfile-${MOLECULE_DISTRO:-debian11}.j2
    privileged: true
    #command: /lib/systemd/systemd
    override_command: false
    #volumes:
    #  - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined
    # cgroup-parent: docker.slice
    # cgroupns: private

provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        checkmk_agent_version: ${MOLECULE_CHECKMK_VERSION:-2.2.0p14}
        checkmk_hostname: ${MOLECULE_CHECKMK_HOSTNAME:-127.0.0.1}
        checkmk_site: ${MOLECULE_CHECKMK_SITE:-SITENAME}
        checkmk_proto: ${MOLECULE_CHECKMK_PROTO:-http}
        download_checkmk_agent_deb: ${MOLECULE_DOWNLOAD_CHECKMK_AGENT_DEB:-false}
        molecule_install_agent_from_server: ${MOLECULE_MOLECULE_INSTALL_AGENT_FROM_SERVER:-true}
        check_mk_logwatch_plugin:
        check_mk_logwatch: false
verifier:
  name: ansible
