---
- hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Update Apt Cache
      apt:
        update_cache: true
      become: true
      when: ansible_os_family == "Debian"
